---
- name: Debian - Workstation
  hosts: localhost
  roles:
    - base
    - docker
    - code
    - golang

  pre_tasks:
    - name: Refresh package cache and upgrade system
      apt:
        cache_valid_time: 3600
        update_cache: yes
        upgrade: yes
