---
# tasks file for roles/code
- name: assert supported build
  assert:
    that:
      - "visual_studio_code_extensions_build in ('stable', 'insiders')"

- name: include package manager specific vars
  with_first_found:
    - '../vars/pkg-mgr/{{ ansible_pkg_mgr }}.yml'
    - ../vars/pkg-mgr/default.yml
  include_vars: '{{ item }}'

- name: install extension cli dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ visual_studio_code_extensions_dependencies }}'

- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install VS Code (apt)
  become: yes
  package:
    name: code
    state: present

- name: Install extensions
  become: no
  visual_studio_code_extensions:
    name: "{{ item }}"
  loop: "{{ visual_studio_code_extensions }}"
  loop_control:
    label: "{{ item }}"
