---
# tasks file for roles/development

- name: Download terraform
  get_url:
    dest: /tmp/terraform.zip
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    sha256sum: "{{ terraform_sha256 }}"

- name: Unarchive terraform
  become: no
  unarchive:
    src: /tmp/terraform.zip
    dest: /tmp

- name: Install terraform binary
  become: yes
  copy:
    src: /tmp/terraform
    dest: /usr/local/bin/terraform
    mode: u+x,g+x,o+x

- name: Download hugo
  get_url:
    dest: /tmp/hugo.tar.gz
    url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_Linux-64bit.tar.gz"
    sha256sum: "{{ hugo_sha256 }}"

- name: Unarchive hugo
  become: no
  unarchive:
    src: /tmp/hugo.tar.gz
    dest: /tmp

- name: Install hugo binary
  become: yes
  copy:
    src: /tmp/hugo
    dest: /usr/local/bin/hugo
    mode: u+x,g+x,o+x

- name: Download gradle
  get_url:
    dest: /tmp/gradle.zip
    url: https://downloads.gradle-dn.com/distributions/gradle-6.0.1-bin.zip
    sha256sum: "{{ gradle_sha256 }}"

- name: Unzip gradle
  become: no
  unarchive:
    src: /tmp/gradle.zip
    dest: /opt
    list_files: yes
  register: archive_contents

- name: Create gradle symbolic link
  become: no
  file:
    src: "{{ archive_contents.files[0].split('/')[0] }}"
    dest: "/opt/gradle"
    state: link

- name: Create gradle /bin symbolic link
  file:
    src: "/opt/gradle/bin/gradle"
    dest: "/usr/local/bin/gradle"
    state: link

- name: Download spark
  get_url:
    dest: /tmp/spark.zip
    url: "https://downloads.apache.org/spark/spark-{{ spark_version }}/spark-{{ spark_version }}-bin-hadoop2.7.tgz"
    sha256sum: "{{ spark_sha256 }}"

- name: Unzip spark
  become: no
  unarchive:
    src: /tmp/spark.zip
    dest: /opt
    list_files: yes
  register: archive_contents

- name: Create spark symbolic link
  become: no
  file:
    src: "{{ archive_contents.files[0].split('/')[0] }}"
    dest: "/opt/spark"
    state: link

- name: Add spark /bin/ to path
  copy:
    dest: /etc/profile.d/spark.sh
    content: "PATH=$PATH:/opt/spark/bin"

- name: Install sceptre
  pip:
    name: sceptre
    executable: pip3
    state: present

- name: Download Rust
  get_url:
    dest: /tmp/rustup.sh
    url: https://static.rust-lang.org/rustup.sh
    sha256sum: "{{ rust_sha256 }}"
  become: no

- name: Install Rust
  shell: /tmp/rustup.sh -y
  args:
    executable: /bin/bash 
    creates: "$HOME/.cargo//bin/rustc"
  become: no

- name: Add SBT key
  become: yes
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
    state: present

- name: install SBT repo (apt)
  become: yes
  apt_repository:
    repo: "deb https://dl.bintray.com/sbt/debian /"
    filename: sbt
    state: present

- name: Install SBT
  package:
    state: present 
    name: sbt