---
# tasks file for roles/base

- name: Install command-line utilities
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Configure touchpad natural-scroll
  gsettings: schema=org.gnome.desktop.peripherals.touchpad key=natural-scroll value=true
  become: no

- name: Configure mouse natural-scroll
  gsettings: schema=org.gnome.desktop.peripherals.mouse key=natural-scroll value=true
  become: no
