---

- name: add virtualbox oracle apt key
  become: yes
  apt_key: url="{{ vbox_key_url }}" state=present
  tags: virtualbox

- name: add virtualbox repository
  become: yes
  apt_repository: repo="{{ vbox_repo }}" state=present mode="0644"
  tags: vbox

- name: install virtualbox
  become: yes
  apt: name="{{ vbox_pkg_name }}" state=present update_cache=yes
  tags: vbox

- name: install virtualbox dkms package
  become: yes
  apt: name="{{ vbox_dkms_pkg_name }}" state=present
  when: vbox_install_dkms
  tags: vbox